

spring:
  profiles:
    active: dev



  jpa:
    hibernate:
      ddl-auto:
---
server:
  port: 8081
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://113.125.103.168:3306/recipes
    username: recipes
    password: qweewqQWEEWQ
  jpa:
    show-sql: true

recipes:
  path: E:\Code\java\recipes\image\
  url: localhost:8081/
---
server:
  port: 8086
spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/recipes
    username: recipes
    password: qweewqQWEEWQ
  jpa:
    show-sql: true

recipes:
  path: /www/wwwroot/pic/
  url: 113.125.103.168:8086/
---

