

spring:
  profiles:
    active: dev
---
server:
  port: 8080
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/recipes
    username: root
    password: root
  jpa:
    show-sql: true

recipes:
  path: E:\Code\java\recipes\image\
---
server:
  port: 8086
spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/recipes
    username: recipes
    password: qweewqQWEEWQ
  jpa:
    show-sql: true

recipes:
  path: /www/wwwroot/pic/

---

